all:
  children:
    group1:
      vars:
        VAR1: "Value 1"
      hosts:
        host1:
          ansible_host: 192.0.2.1
          ansible_ssh_user: user1
          ansible_ssh_password: password1
